### ISSUE TITLE
failed snowplow validation on non-required fields

### ISSUE THREAD

**Issue by aniham** [adobe/commerce-events#106]
@ryanhissey hyva is having issues setting shopping cart context with `subtotalIncludingTax` and `subtotalExcludingTax` (non-required fields) missing. it's causing conversion tracking issues with hyva as all events that require a shopping cart context are sent to the bad bucket in sp

**Comment by ryanhissey** [comment]
Hi, 

Thanks for creating this issue here @aniham. It would be great if we could get this PR Merged and ready so we can push forward with the remaining Event issues.

**Comment by aniham** [comment]
@ryanhissey this is resolved with https://github.com/adobe/commerce-events/pull/128
