### ISSUE TITLE
Links in storefront-events-sdk README are broken

### ISSUE THREAD

**Issue by hannessolo** [adobe/commerce-events#122]
### Expected Behaviour

Can follow links in https://github.com/adobe/commerce-events/blob/main/packages/storefront-events-sdk/README.md to examples and schemas.

### Actual Behaviour

Links have `commerce-events-sdk` in the path instead of `storefront-events-sdk` and lead to a 404.

Example: https://github.com/adobe/commerce-events/blob/main/packages/commerce-events-sdk/src/types/schemas/shoppingCart.ts instead of https://github.com/adobe/commerce-events/blob/main/packages/storefront-events-sdk/src/types/schemas/shoppingCart.ts

**Comment by aniham** [comment]
@hannessolo changes merged, sorry for the delay
