### ISSUE TITLE
Problem with items without price

### ISSUE THREAD

**Issue by johan-lindahl** [adobe/commerce-events#74]
I have experienced that recommendation items sometimes are returned by Adobe Sensei without price information.

The response from https://commerce.adobe.io/recs/v1/precs/preconfigured should return a price section such as,
```
"prices": {
                        "maximum": {
                            "finalAdjustments": [],
                            "regular": 699.0,
                            "regularAdjustments": [],
                            "final": 699.0
                        },
                        "minimum": {
                            "finalAdjustments": [],
                            "regular": 699.0,
                            "regularAdjustments": [],
                            "final": 699.0
                        }
                    },
```

But for some products I get the following in the response,

```
"prices": {},
```

This creates problems for the recommendedItem context and it will return a type error. The crash (type error) occurs in the following code section.

https://github.com/adobe/commerce-events/blob/0a1eafe77160f498ebf36cd41d6dc0dfddcacc35/packages/storefront-events-collector/src/contexts/recommendedItem.ts#L47

I think that it would be helpful to improve error handling, not sure exactly what can be done since the problem seems to be on the server side. I suggest that such "broken" items without price are filtered out by the recommended item context to avoid the entire app to crash when such item is recommended.

**Comment by aniham** [comment]
@johan-lindahl this issue was resolved in 1.3.1! feel free to try out and let us know if anything seems off!
